import React from "react";
import colors from "../../../../shared/_colors.module.scss";
import { motion } from "framer-motion";
import styles from "../../Blueprint.module.scss";

const variants = {
  hidden: { opacity: 0, pathLength: 0 },
  drawSVG: { opacity: 1, pathLength: 1, transition: { duration: 1 } },
  renderImage: { opacity: 0, transition: { duration: 1 } },
};

const AppBlueprint = () => {
  return (
    <motion.svg
      width="100%"
      height="100%"
      viewBox="0 0 960 800"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={styles.svg}
      style={{ left: "5px", top: "1px" }}
    >
      <motion.rect
        variants={variants}
        x="1.5"
        y="1.5"
        width="386"
        height="786"
        rx="48.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="557.5"
        y="1.5"
        width="386"
        height="786"
        rx="48.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="3"
        y1="747.5"
        x2="386"
        y2="747.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="559"
        y1="747.5"
        x2="942"
        y2="747.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="125.5"
        y1="749"
        x2="125.5"
        y2="789"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="681.5"
        y1="749"
        x2="681.5"
        y2="789"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="265.5"
        y1="747"
        x2="265.5"
        y2="787"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="821.5"
        y1="747"
        x2="821.5"
        y2="787"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="54.5"
        cy="767.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="615.5"
        cy="767.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="333.5"
        cy="767.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="889.5"
        cy="767.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="179.5"
        y="753.5"
        width="28"
        height="28"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="739.5"
        y="753.5"
        width="28"
        height="28"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="609.5"
        y="614.5"
        width="84"
        height="66"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="835.5"
        y="614.5"
        width="46"
        height="66"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="708.5"
        y="706.5"
        width="15"
        height="15"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="734.5"
        y="706.5"
        width="15"
        height="15"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="760.5"
        y="706.5"
        width="15"
        height="15"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="786.5"
        y="706.5"
        width="15"
        height="15"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="20.5"
        y="43.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="149.5"
        y="43.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="278.5"
        y="43.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="20.5"
        y="247.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="149.5"
        y="247.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="278.5"
        y="247.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="20.5"
        y="451.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="149.5"
        y="451.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="278.5"
        y="451.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="20.5"
        y="655.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="149.5"
        y="655.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="278.5"
        y="655.5"
        width="90"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="37.5"
        y="43.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="166.5"
        y="43.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="295.5"
        y="43.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="37.5"
        y="247.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="166.5"
        y="247.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="295.5"
        y="247.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="37.5"
        y="451.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="166.5"
        y="451.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="295.5"
        y="451.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="37.5"
        y="655.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="74.5"
        y="43.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="203.5"
        y="43.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="332.5"
        y="43.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="74.5"
        y="247.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="203.5"
        y="247.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="332.5"
        y="247.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="74.5"
        y="451.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="203.5"
        y="451.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="332.5"
        y="451.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="74.5"
        y="655.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="166.5"
        y="655.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="202.5"
        y="655.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="295.5"
        y="655.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="331.5"
        y="655.5"
        width="18"
        height="90"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="20.5"
        y="67.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="149.5"
        y="67.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="278.5"
        y="67.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="20.5"
        y="271.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="149.5"
        y="271.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="278.5"
        y="271.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="20.5"
        y="475.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="149.5"
        y="475.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="278.5"
        y="475.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="20.5"
        y="679.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="149.5"
        y="679.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="278.5"
        y="679.5"
        width="90"
        height="22"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="20"
        y1="111.5"
        x2="111"
        y2="111.5"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="149"
        y1="111.5"
        x2="240"
        y2="111.5"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="278"
        y1="111.5"
        x2="369"
        y2="111.5"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="20"
        y1="315.5"
        x2="111"
        y2="315.5"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="149"
        y1="315.5"
        x2="240"
        y2="315.5"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="278"
        y1="315.5"
        x2="369"
        y2="315.5"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="20"
        y1="519.5"
        x2="111"
        y2="519.5"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="149"
        y1="519.5"
        x2="240"
        y2="519.5"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="278"
        y1="519.5"
        x2="369"
        y2="519.5"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="20"
        y1="723.5"
        x2="111"
        y2="723.5"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="149"
        y1="723.5"
        x2="240"
        y2="723.5"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="278"
        y1="723.5"
        x2="369"
        y2="723.5"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="55.5"
        cy="78.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="184.5"
        cy="78.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="295.5"
        cy="100.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="313.5"
        cy="100.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="37.5"
        cy="305.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="184.5"
        cy="327.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="313.5"
        cy="327.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="55.5"
        cy="508.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="184.5"
        cy="509.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="313.5"
        cy="486.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="55.5"
        cy="713.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="65.5"
        cy="172.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="194.5"
        cy="172.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="323.5"
        cy="172.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="65.5"
        cy="376.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="194.5"
        cy="376.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="323.5"
        cy="376.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="65.5"
        cy="580.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="194.5"
        cy="580.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="323.5"
        cy="580.5"
        r="14"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="74.5"
        cy="78.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="203.5"
        cy="78.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="332.5"
        cy="78.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="55.5"
        cy="305.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="203.5"
        cy="327.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="332.5"
        cy="327.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="74.5"
        cy="508.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="203.5"
        cy="509.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="295.5"
        cy="509.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="74.5"
        cy="713.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="92.5"
        cy="78.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="221.5"
        cy="56.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="221.5"
        cy="327.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="350.5"
        cy="305.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="92.5"
        cy="508.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="221.5"
        cy="486.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="350.5"
        cy="464.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="92.5"
        cy="690.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="202.5"
        cy="691.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="239.5"
        cy="690.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="368.5"
        cy="668.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="331.5"
        cy="690.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="349.5"
        cy="713.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.circle
        variants={variants}
        cx="220.5"
        cy="713.5"
        r="6"
        stroke={colors.boldBlue}
      />
      <motion.line
        variants={variants}
        x1="58"
        y1="140.5"
        x2="74"
        y2="140.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="187"
        y1="140.5"
        x2="203"
        y2="140.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="316"
        y1="140.5"
        x2="332"
        y2="140.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="58"
        y1="344.5"
        x2="74"
        y2="344.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="187"
        y1="344.5"
        x2="203"
        y2="344.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="316"
        y1="344.5"
        x2="332"
        y2="344.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="58"
        y1="548.5"
        x2="74"
        y2="548.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="187"
        y1="548.5"
        x2="203"
        y2="548.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="316"
        y1="548.5"
        x2="332"
        y2="548.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="273.5"
        y="50.5"
        width="100"
        height="12"
        rx="4.5"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="15.5"
        y="254.5"
        width="100"
        height="12"
        rx="4.5"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="161.5"
        y="276.5"
        width="84"
        height="12"
        rx="4.5"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="290.5"
        y="277.5"
        width="84"
        height="12"
        rx="4.5"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="32.5"
        y="458.5"
        width="84"
        height="12"
        rx="4.5"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="32.5"
        y="662.5"
        width="84"
        height="12"
        rx="4.5"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="161.5"
        y="458.5"
        width="84"
        height="12"
        rx="4.5"
        stroke={colors.boldBlue}
      />
      <motion.rect
        variants={variants}
        x="635.5"
        y="243.5"
        width="238"
        height="239"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="681.5"
        y="243.5"
        width="48"
        height="239"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="622.5"
        y="205.5"
        width="24"
        height="32"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="635.5"
        y="309.5"
        width="238"
        height="57"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.rect
        variants={variants}
        x="778.5"
        y="243.5"
        width="48"
        height="239"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="634"
        y1="425.5"
        x2="875"
        y2="425.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="730"
        cy="338"
        r="14.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="778"
        cy="338"
        r="14.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="827"
        cy="338"
        r="14.5"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.line
        variants={variants}
        x1="681"
        y1="42"
        x2="832"
        y2="42"
        stroke={colors.boldBlue}
        stroke-width="10"
      />
      <motion.line
        variants={variants}
        x1="731"
        y1="168.5"
        x2="778"
        y2="168.5"
        stroke={colors.boldBlue}
        stroke-width="5"
      />
      <motion.line
        variants={variants}
        x1="731"
        y1="504"
        x2="778"
        y2="504"
        stroke={colors.boldBlue}
        stroke-width="8"
      />
      <motion.circle
        variants={variants}
        cx="680.5"
        cy="221.5"
        r="16"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.circle
        variants={variants}
        cx="874.5"
        cy="221.5"
        r="16"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
      <motion.path
        variants={variants}
        d="M459.5 370.153L506 397L459.5 423.847L459.5 370.153Z"
        stroke={colors.boldBlue}
        stroke-width="3"
      />
    </motion.svg>
  );
};

export default AppBlueprint;
