import React from "react";
import colors from "../../shared/_colors.module.scss";
import { motion } from "framer-motion";

const variants = {
  hidden: { opacity: 0, pathLength: 0 },
  draw: { opacity: 1, pathLength: 1, transition: { duration: 1.2 } },
  imagesAppear: { opacity: 0, transition: { duration: 1 } },
};

const AppBlueprint = () => {
  return (
    <svg
      width="100%"
      height="100%"
      viewBox="0 0 552 1080"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g id="app-blueprint">
        <motion.rect
          variants={variants}
          id="app-container"
          x="1.5"
          y="1.5"
          width="549"
          height="1077"
          stroke={colors.boldBlue}
          stroke-width="3"
          transform="scale(1, -1) translate(0, -1079)"
        />
        <motion.line
          variants={variants}
          id="title-bottom-border"
          y1="85.5"
          x2="552"
          y2="85.5"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="notification-board"
          x="285.5"
          y="97.5"
          width="250"
          height="160"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="movelist"
          x="16.5"
          y="97.5"
          width="251"
          height="339"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="settings-button"
          x="285.5"
          y="273.5"
          width="250"
          height="50"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="skip-button"
          x="285.5"
          y="329.5"
          width="250"
          height="50"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="hint-button"
          x="285.5"
          y="386.5"
          width="250"
          height="50"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="rank-8"
          x="10.5"
          y="453.5"
          width="530"
          height="63"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="file-a"
          x="10.5"
          y="453.5"
          width="64"
          height="531"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="file-c"
          x="144.5"
          y="454.5"
          width="64"
          height="531"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="file-e"
          x="277.5"
          y="454.5"
          width="64"
          height="531"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="file-g"
          x="411.5"
          y="454.5"
          width="64"
          height="531"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="rank-6"
          x="11.5"
          y="587.5"
          width="530"
          height="63"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="rank-4"
          x="10.5"
          y="721.5"
          width="530"
          height="63"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="rank-2"
          x="10.5"
          y="855.5"
          width="530"
          height="63"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.rect
          variants={variants}
          id="board-outline"
          x="11.5"
          y="453.5"
          width="530"
          height="532"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.circle
          variants={variants}
          id="top-nav-info"
          cx="369"
          cy="47"
          r="13.5"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.circle
          variants={variants}
          id="top-nav-help"
          cx="439"
          cy="47"
          r="13.5"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.circle
          variants={variants}
          id="top-nav-settings"
          cx="510"
          cy="47"
          r="13.5"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.line
          variants={variants}
          id="title-line-1"
          x1="27"
          y1="37.5"
          x2="113"
          y2="37.5"
          stroke={colors.boldBlue}
          stroke-width="5"
        />
        <motion.line
          variants={variants}
          id="subtitle-line"
          x1="27"
          y1="61"
          x2="55"
          y2="61"
          stroke={colors.boldBlue}
          stroke-width="4"
        />
        <motion.line
          variants={variants}
          id="title-line-2"
          x1="124"
          y1="37.5"
          x2="173"
          y2="37.5"
          stroke={colors.boldBlue}
          stroke-width="5"
        />
        <motion.circle
          variants={variants}
          id="home-test"
          cx="276.5"
          cy="1033.5"
          r="32"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.circle
          variants={variants}
          id="home-record"
          cx="91.5"
          cy="1033.5"
          r="32"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
        <motion.circle
          variants={variants}
          id="home-list"
          cx="459.5"
          cy="1033.5"
          r="32"
          stroke={colors.boldBlue}
          stroke-width="3"
        />
      </g>
    </svg>
  );
};

export default AppBlueprint;
